using System.Linq; // Corvax-TTS
using Content.Shared.Administration;
using Content.Shared.CCVar; // Corvax-TTS
using Content.Shared.Corvax.TTS; // Corvax-TTS
using Robust.Client.AutoGenerated;
using Robust.Client.UserInterface;
using Robust.Client.UserInterface.Controls;
using Robust.Client.UserInterface.CustomControls;
using Robust.Client.UserInterface.XAML;
using Robust.Shared.Configuration; // Corvax-TTS
using Robust.Shared.Prototypes; // Corvax-TTS
using Robust.Shared.Utility;

namespace Content.Client.Administration.UI
{
    [GenerateTypedNameReferences]
    public sealed partial class AdminAnnounceWindow : DefaultWindow
    {
        [Dependency] private ILocalizationManager _localization = default!;
// Corvax-TTS-start:
        [Dependency] private IConfigurationManager _cfg = default!;

        private readonly List<TTSVoicePrototype> _voices;
// Corvax-TTS-end.

        public AdminAnnounceWindow()
        {
            RobustXamlLoader.Load(this);
            IoCManager.InjectDependencies(this);

            Announcement.Placeholder = new Rope.Leaf(_localization.GetString("admin-announce-announcement-placeholder"));
            AnnounceMethod.AddItem(_localization.GetString("admin-announce-type-station"));
            AnnounceMethod.SetItemMetadata(0, AdminAnnounceType.Station);
            AnnounceMethod.AddItem(_localization.GetString("admin-announce-type-server"));
            AnnounceMethod.SetItemMetadata(1, AdminAnnounceType.Server);
            AnnounceMethod.AddItem(_localization.GetString("admin-announce-type-antag"));  // Frontier
            AnnounceMethod.SetItemMetadata(2, AdminAnnounceType.Antag);  // Frontier
            AnnounceMethod.OnItemSelected += AnnounceMethodOnOnItemSelected;
            VoiceSelector.OnItemSelected += args => VoiceSelector.SelectId(args.Id);
            Announcement.OnKeyBindUp += AnnouncementOnOnTextChanged;

            var ttsEnabled = _cfg.GetCVar(CCVars.TTSEnabled);
            EnableTTS.Visible = ttsEnabled;
            EnableTTS.Pressed = ttsEnabled;
            VoiceSelector.Visible = ttsEnabled;

            var protoManager = IoCManager.Resolve<IPrototypeManager>();
            _voices = protoManager
                .EnumeratePrototypes<TTSVoicePrototype>()
                .OrderBy(o => Loc.GetString(o.Name))
                .ToList();

            for (var i = 0; i < _voices.Count; i++)
            {
                VoiceSelector.AddItem(Loc.GetString(_voices[i].Name), i);
                VoiceSelector.SetItemMetadata(i, _voices[i].ID);
            }

            if (_voices.Count > 0)
                VoiceSelector.SelectId(0);
        }

        private void AnnouncementOnOnTextChanged(GUIBoundKeyEventArgs args)
        {
            AnnounceButton.Disabled = Rope.Collapse(Announcement.TextRope).TrimStart() == "";
        }

        private void AnnounceMethodOnOnItemSelected(OptionButton.ItemSelectedEventArgs args)
        {
            AnnounceMethod.SelectId(args.Id);
            Announcer.Editable = ((AdminAnnounceType?)args.Button.SelectedMetadata ?? AdminAnnounceType.Station) == AdminAnnounceType.Station
            || ((AdminAnnounceType?)args.Button.SelectedMetadata ?? AdminAnnounceType.Antag) == AdminAnnounceType.Antag; // Frontier
        }
    }
}
