using System.Linq; // Corvax-TTS
using Content.Client.UserInterface.Controls;
using Content.Shared.CCVar; // Corvax-TTS
using Content.Shared.Corvax.TTS; // Corvax-TTS
using Content.Shared.Speech;
using Robust.Client.AutoGenerated;
using Robust.Client.UserInterface.CustomControls;
using Robust.Client.UserInterface.XAML;
using Robust.Shared.Configuration; // Corvax-TTS
using Robust.Shared.Prototypes;

namespace Content.Client.VoiceMask;

[GenerateTypedNameReferences]
public sealed partial class VoiceMaskNameChangeWindow : FancyWindow
{
    public Action<string>? OnNameChange;
    public Action<string?>? OnVerbChange;
    public Action<string>? OnVoiceChange; // Corvax-TTS

    private List<(string, string)> _verbs = new();
    private List<TTSVoicePrototype> _voices = new(); // Corvax-TTS

    private string? _verb;
    private string? _voice;

    public VoiceMaskNameChangeWindow()
    {
        RobustXamlLoader.Load(this);

        NameSelectorSet.OnPressed += _ =>
        {
            OnNameChange?.Invoke(NameSelector.Text);
        };

        SpeechVerbSelector.OnItemSelected += args =>
        {
            OnVerbChange?.Invoke((string?) args.Button.GetItemMetadata(args.Id));
            SpeechVerbSelector.SelectId(args.Id);
        };
// Corvax-TTS-start:

        TTSContainer.Visible = IoCManager.Resolve<IConfigurationManager>().GetCVar(CCVars.TTSEnabled);

        VoiceSelector.OnItemSelected += args =>
        {
            VoiceSelector.SelectId(args.Id);
            if (args.Button.GetItemMetadata(args.Id) is string voice)
                OnVoiceChange?.Invoke(voice);
        };
// Corvax-TTS-end.
    }

    public void ReloadVerbs(IPrototypeManager proto)
    {
        foreach (var verb in proto.EnumeratePrototypes<SpeechVerbPrototype>())
        {
            _verbs.Add((Loc.GetString(verb.Name), verb.ID));
        }
        _verbs.Sort((a, b) => a.Item1.CompareTo(b.Item1));
    }

    public void AddVerbs()
    {
        SpeechVerbSelector.Clear();

        AddVerb(Loc.GetString("chat-speech-verb-name-none"), null);
        foreach (var (name, id) in _verbs)
        {
            AddVerb(name, id);
        }
    }

    private void AddVerb(string name, string? verb)
    {
        var id = SpeechVerbSelector.ItemCount;
        SpeechVerbSelector.AddItem(name);
        if (verb is {} metadata)
            SpeechVerbSelector.SetItemMetadata(id, metadata);

        if (verb == _verb)
            SpeechVerbSelector.SelectId(id);
    }

//     public void UpdateState(string name, string? verb) // Commented by Corvax-TTS
// Corvax-TTS-start:
    public void ReloadVoices(IPrototypeManager proto)
    {
        _voices = proto
            .EnumeratePrototypes<TTSVoicePrototype>()
            .Where(o => o.RoundStart)
            .OrderBy(o => Loc.GetString(o.Name))
            .ToList();

        VoiceSelector.Clear();

        for (var i = 0; i < _voices.Count; i++)
        {
            VoiceSelector.AddItem(Loc.GetString(_voices[i].Name));
            VoiceSelector.SetItemMetadata(i, _voices[i].ID);
        }
    }

    public void UpdateState(string name, string? verb, string voice)
// Corvax-TTS-end.
    {
        NameSelector.Text = name;
        _verb = verb;
        _voice = voice; // Corvax-TTS

        for (int id = 0; id < SpeechVerbSelector.ItemCount; id++)
        {
            if (string.Equals(verb, SpeechVerbSelector.GetItemMetadata(id)))
            {
                SpeechVerbSelector.SelectId(id);
                break;
            }
        }
// Corvax-TTS-start:

        for (int id = 0; id < VoiceSelector.ItemCount; id++)
        {
            if (string.Equals(_voice, VoiceSelector.GetItemMetadata(id)))
            {
                VoiceSelector.SelectId(id);
                break;
            }
        }
// Corvax-TTS-end.
    }
}
